server:
  port: 8081
  servlet:
    context-path: /api

#使用下面数据源配置
#spring:
#    datasource:
#        name: mysql_test
#        type: com.alibaba.druid.pool.DruidDataSource
#        #druid相关配置
#        druid:
          #监控统计拦截的filters
#          filters: stat
#          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
#          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#          username: root
#          password: yijun123456
          #配置初始化大小/最小/最大
#          initial-size: 1
#          min-idle: 1
#          max-active: 20
          #获取连接等待超时时间
#          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
#          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
#          min-evictable-idle-time-millis: 300000
#          validation-query: SELECT 'x'
#          test-while-idle: true
#          test-on-borrow: false
#          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#          pool-prepared-statements: false
#          max-pool-prepared-statement-per-connection-size: 20
#数据源配置 多数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      base:  #默认数据源base
        url: jdbc:mysql://106.14.82.116:3306/med?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: yijun123456
      customer:  #数据源customer
        url: jdbc:mysql://106.14.82.116:3306/med?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: yijun123456
      dm:  #数据源dm
        url: jdbc:mysql://106.14.82.116:3306/med?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: yijun123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.winterchen.model
# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.springblade.**.entity;com.winterchen.model
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

taobao:
#沙箱环境 http://gw.api.tbsandbox.com/router/rest
  server-url: http://gw.api.taobao.com/router/rest
  tbk:
    appkey: 28254994
    appsecret: dfa16050ca19cb43903a76edbe3d30f6
  baichuan:
    appkey: 23183740
    appsecret: a5858c0fb379e727ecd8df8cea054219
  adzone-id: 109948000102
  site_id: 1237850014
zhetaoke_appkey: 7bf4d83219064435952d22edcd06d96c

